"""changed column lenght

Revision ID: 11a51b8a9144
Revises: f29508a35df9
Create Date: 2024-08-19 17:14:25.128411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a51b8a9144'
down_revision = 'f29508a35df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=1000),
               existing_nullable=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=1000),
               existing_nullable=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###
