"""new content under the Task model

Revision ID: 2065020abf63
Revises: c393e152bc66
Create Date: 2024-08-20 12:02:41.125731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2065020abf63'
down_revision = 'c393e152bc66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
