"""finished the last change

Revision ID: c393e152bc66
Revises: 97a07f69c7f9
Create Date: 2024-08-19 23:43:59.529783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c393e152bc66'
down_revision = '97a07f69c7f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_project_category", 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint("fk_project_category", type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
